/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package expedisi_04111055;
import expedisi_04111055.master.*;
import expedisi_04111055.utility.*;
import expedisi_04111055.List_view.*;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
/**
 *
 * @author ArDhiye
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setSize(1200, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        mnDaftar = new javax.swing.JMenu();
        itemCustomer = new javax.swing.JMenuItem();
        itemKapal = new javax.swing.JMenuItem();
        itemPelayaran = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem14.setText("Daftar User");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem15.setText("About");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        mnDaftar.setText("Master");

        itemCustomer.setText("Master Customer");
        itemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCustomerActionPerformed(evt);
            }
        });
        mnDaftar.add(itemCustomer);

        itemKapal.setText("Master Kapal");
        itemKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKapalActionPerformed(evt);
            }
        });
        mnDaftar.add(itemKapal);

        itemPelayaran.setText("Master Pelayaran");
        itemPelayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPelayaranActionPerformed(evt);
            }
        });
        mnDaftar.add(itemPelayaran);

        jMenuItem1.setText("Master Kota");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnDaftar.add(jMenuItem1);

        jMenuItem2.setText("Master Penerima");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnDaftar.add(jMenuItem2);

        jMenuItem3.setText("Master Subcon");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnDaftar.add(jMenuItem3);

        jMenuItem4.setText("Master Transportir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnDaftar.add(jMenuItem4);

        jMenuItem5.setText("Master Agen Door");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnDaftar.add(jMenuItem5);

        jMenuBar1.add(mnDaftar);

        jMenu3.setText("Daftar");

        jMenuItem7.setText("Daftar Customers");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Daftar Penerima");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Daftar Agen Door");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Daftar Pelayaran");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Daftar Subcon");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Daftar Kapal");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Daftar Transportir");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Transaksi");

        jMenuItem6.setText("Creat Job");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCustomerActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mCustomer mc=new mCustomer();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mc.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mc);
        Dimension sreen=this.getSize();
        Dimension frame=mc.getSize();
        mc.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_itemCustomerActionPerformed

    private void itemKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKapalActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mKapal mk=new mKapal();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mk.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mk);
        Dimension sreen=this.getSize();
        Dimension frame=mk.getSize();
        mk.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mk.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_itemKapalActionPerformed

    private void itemPelayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPelayaranActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mPelayaran mp=new mPelayaran();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mp.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mp);
        Dimension sreen=this.getSize();
        Dimension frame=mp.getSize();
        mp.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPelayaranActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mKota mk=new mKota();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mk.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mk);
        Dimension sreen=this.getSize();
        Dimension frame=mk.getSize();
        mk.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mk.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mPenerima mpn=new mPenerima();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mpn.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mpn);
        Dimension sreen=this.getSize();
        Dimension frame=mpn.getSize();
        mpn.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mpn.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mSubcon ms=new mSubcon();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(ms.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(ms);
        Dimension sreen=this.getSize();
        Dimension frame=ms.getSize();
        ms.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        ms.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mTransportir mt=new mTransportir();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mt.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mt);
        Dimension sreen=this.getSize();
        Dimension frame=mt.getSize();
        mt.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mt.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        mAgendoor mad=new mAgendoor();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(mad.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(mad);
        Dimension sreen=this.getSize();
        Dimension frame=mad.getSize();
        mad.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mad.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        createJob cj=new createJob();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(cj.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(cj);
        Dimension sreen=this.getSize();
        Dimension frame=cj.getSize();
        cj.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        cj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Customers lc=new list_Customers();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(lc.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(lc);
        Dimension sreen=this.getSize();
        Dimension frame=lc.getSize();
        lc.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        lc.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Penerima lp=new list_Penerima();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(lp.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(lp);
        Dimension sreen=this.getSize();
        Dimension frame=lp.getSize();
        lp.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        lp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Agendoor la=new list_Agendoor();
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(la.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jDesktopPane1.add(la);
        Dimension sreen=this.getSize();
        Dimension frame=la.getSize();
        la.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        la.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
     JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Pelayaran lp = new list_Pelayaran();
        
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(lp.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        jDesktopPane1.add(lp);
        Dimension sreen=this.getSize();
        Dimension frame=lp.getSize();
        lp.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        lp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Subcon ls = new list_Subcon();
        
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(ls.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        jDesktopPane1.add(ls);
        Dimension sreen=this.getSize();
        Dimension frame=ls.getSize();
        ls.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        ls.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Kapal lk = new list_Kapal();
        
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(lk.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        jDesktopPane1.add(lk);
        Dimension sreen=this.getSize();
        Dimension frame=lk.getSize();
        lk.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        lk.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        list_Transportir lt = new list_Transportir();
        
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(lt.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        jDesktopPane1.add(lt);
        Dimension sreen=this.getSize();
        Dimension frame=lt.getSize();
        lt.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        lt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        daftaruser mc=new daftaruser();
        jDesktopPane1.add(mc);
        Dimension sreen=this.getSize();
        Dimension frame=mc.getSize();
        mc.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        mc.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        JInternalFrame[] frames = this.jDesktopPane1.getAllFrames();
        About lt = new About();
        
        for (JInternalFrame frm : frames) {
            if (frm.getTitle().equals(lt.getTitle())){
                try {
                    frm.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        jDesktopPane1.add(lt);
        Dimension sreen=this.getSize();
        Dimension frame=lt.getSize();
        lt.setLocation((sreen.width=frame.width)/5,(sreen.height=frame.height)/5);
        lt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCustomer;
    private javax.swing.JMenuItem itemKapal;
    private javax.swing.JMenuItem itemPelayaran;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnDaftar;
    // End of variables declaration//GEN-END:variables
}
